AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

require:
  - rubocop-minitest
  - rubocop-performance

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/WordArray:
  EnforcedStyle: brackets
